# <a rel="me" href="https://social.ohmyposh.dev/@releasebot">Mastodon</a>

name: Mastodon
on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notes 📝
        id: notes
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410
        with:
          result-encoding: string
          script: |
            notes = context.payload.release.body

            // replace all non-supported characters
            notes = notes.replaceAll('###', '')
            notes = notes.replaceAll('**', '')
            notes = notes.replace(/ \(\[[0-9a-z]+\]\(.*\)/g, '')
            notes = notes.trim()
            return notes
      - name: Bluesky 🌤️
        id: bluesky
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410
        with:
          script: |
            import pkg from '@atproto/api';
            const { BskyAgent, RichText } = pkg;

            const agent = new BskyAgent({ service: 'https://bsky.social' })
            await agent.login({identifier: '${{ secrets.BLUESKY_IDENTIFIER }}', password: '${{ secrets.BLUESKY_PASSWORD }}'})

            const postBody = `📦 ${{ github.event.release.name }}

            ${{steps.notes.outputs.result}}

            ${{ github.event.release.html_url }}

            #ohmyposh #oss #cli #opensource`;

            const rt = new RichText({text: postBody})
            await rt.detectFacets(agent)

            const post = {
              $type: 'app.bsky.feed.post',
              text: rt.text,
              facets: rt.facets,
              createdAt: new Date().toISOString()
            }

            await agent.post(post)
      - name: Toot 🐘
        uses: cbrgm/mastodon-github-action@d98ab3376f941df14d37d5737961de431c0838c6
        with:
          message: |
            📦 ${{ github.event.release.name }}

            ${{steps.notes.outputs.result}}

            ${{ github.event.release.html_url }}

            #ohmyposh #oss #cli #opensource
          visibility: "public"
        env:
          MASTODON_URL: "https://social.ohmyposh.dev/"
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
